apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: loop-nuke
spec:
  template:
    spec:
      containers:
        - image: ko://github.com/JeffNeff/loopNuke/cmd/loopNuke/
          env:
